<style type="text/css">
	#alumni_content {
 		margin-top: 25px;
 	}
</style>
<main id="alumni_content">
	<section id="system_update_hero"  class="container" style="margin-top: -25px;">
		<div class="card" style="background: transparent; border: none;">
   		<img decoding="async" src="http://localhost/public_html/public/resources/images/general/alert/system_update.png" class="card-img-top w-100" />
		</div>
  </section>
</main>