<style type="text/css">
	.card {
		background: transparent; 
		border-radius: 0px;
	}
	.card_header {
  		background-image: linear-gradient(to right, #996515, #b4813f); 
  		opacity: .9;
  	}
	.card_title {
		color: #ffffff; 
		font-size: 20px!important;
		font-weight: bolder!important; 
		opacity: .8;
	}
	.details_text {
		line-height: 25px;
		font-size: 15px;
  	text-align: justify;
  	text-justify: inter-word;
  	opacity: 1!important;
  	padding: 5px;
	}

</style>

<main>
	<section id="school_bg" >
  	<div id="bg_img" >
	    <img src="http://localhost/public_html/public/resources/images/slider/hero/school_smb.PNG" class="card-img-top w-100"/>
    </div> 
  </section>
	<section class="mt-2">
		<div class="container">
			<div class="row">
				<div class="col-md-4 mb-3">			
					<div class="card">
						<div class="card-header card_header"></div>
						<img src="http://localhost/public_html/public/resources/images/goldenminds-seal.png" class="card-img-top w-100" />
						<div class="card-body">
							<p spellcheck="true" class="details_text" >
							...where passion of imparting knowledge and preserving values that nurture a person's character to help him become a better citizen
							There are five elements that summarize the totality of the institution.
							Building a community of lifelong learners!
							Dedicated Educators
							<br/><br/>
							We know that learning is easier when you have an excellent teacher. That's why most of our educators have achieved an advanced degree in their field. Our faculty are passionate about the subjects they teach and bring this enthusiasm into their lessons.
				      </p>
				    </div>
					</div>
				</div>
				<div class="col-md-8">
					<div class="card border-0">
						<div class="card-header card_header">
							<span class="card_title">&nbsp;<i>Elements</i></span>
						</div>
					  <table class="table" style="border: 1px solid #DDDDDD;">
		  				<tr>
						    <td>
						    	<img src="http://localhost/public_html/public/resources/images/general/shield.jpg" width="100px" height="125px" > 
						    </td>
						    <td>
						    	<p class="details_text">
						    		The <font color="red">Shield </font> symbolizes our eagerness to protect our students' concern and make them realize the multitude of learning opportunuties that lies ahead. 
						    	</p>
						    </td>
		  				</tr>
					  	<tr>
						    <td> 
						    	<img src="http://localhost/public_html/public/resources/images/general/torch1.jpeg" width="100px" height="125px">  
						    </td>
						    <td> 
						    	<p class="details_text">
						    		The <font color="red">Torch </font> conveys the intention of this institution to enlighten each and everyone's mind and "fire-up" the learner's spirit within our students.
						    	</p>   
						    </td>
					  	</tr>
						  <tr>
						    <td>  
						    	<img src="http://localhost/public_html/public/resources/images/general/gear.jpeg" width="100px" height="125">   
						    </td>
						    <td>
						    	<p class="details_text">
						    		The <font color="red">Gear</font>  is the mirror of technology and modernization thus our aim is to make them ready and updated of the current trends.
						    	</p> 
						    </td>
						  </tr>
							<tr>
							  <td>  
							  	<img src="http://localhost/public_html/public/resources/images/general/plume.jpg" width="100px" height="125px">   
							  </td>
							  <td>
							  	<p class="details_text">
							  		In every student's heart and mind lies the hope of being heard and the ability to voice-out valuable opinions as symbolized by the <font color="red"> Plume </font> 
							  	</p>  
							  </td>
							</tr>
							<tr>
								<td>
									<img src="http://localhost/public_html/public/resources/images/general/book.jpg" width="100px" height="125px">
								</td>
								<td>
									<p class="details_text">
										Our mission of imparting knowledge and skills to our students is characterized by the <font color="red"> "Book of Wisdom"</font>. This Book signifies the <font color="red">"Holy Bible"</font> as spiritual guided or any holy materials a person's faith dictates.   
									</p> 
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>
</main>