<style type="text/css">
	.card {
		background: transparent; 
		border-radius: 0px;
	}
	.card_header {
  		background-image: linear-gradient(to right, #996515, #b4813f); 
  		opacity: .9;
  	}
	.card_title {
		color: #ffffff; 
		font-size: 20px!important;
		font-weight: bolder!important; 
		opacity: .8;
	}
	.card_paragraph {
		line-height: 25px;
		font-size: 15px;
		text-align: justify;
		text-justify: inter-word;
		opacity: 1!important;
		padding: 5px;
	}
	table {
		border: 1px solid #F3F3F3!important;
	}
	td.td_title {
		padding: 10px!important;
	}
	td.td_desc {
		padding: 5px!important;
	}
</style>

<main>
	<section id="school_bg" >
  	<div id="bg_img" >
	    <img src="http://localhost/public_html/public/resources/images/slider/hero/school_smb.PNG" class="card-img-top w-100" />
    </div> 
  </section>
	<section class="mt-2">
		<div class="container">
			<div class="row">
				<div class="col-md-6 mb-3">
					<div class="card">

						<div class="card-header card_header">
							<span class="card_title">&nbsp;<i>Vision</i></span>
						</div>
						<div class="card-body">
							<p spellcheck="true" class="card_paragraph">
								We are envisioned to cultivate and ignite a dynamic learning environtment that equips students with knowledge and skills to become ready in the fast changing technology, to seek excellence in their choosen endeavour, develops critical thinking and fair judgement.
					    </p>
				  	</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card">
						<div class="card-header card_header">
							<span class="card_title">&nbsp;<i>Mission</i></span>
						</div>

						<div class="card-body">
							<p spellcheck="true" class="card_paragraph">
								To create a supportive environment that nurture and empowers the learning spirit of our students to be more productive, goal-driven, academically explorative and thus become a good contributor to his environment fostering respect and love for others.
					    </p>
				  	</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<div class="card mt-3">
						<div class="card-header card_header">
							<span class="card_title">&nbsp;<i>Philosophy</i></span>
						</div>
						<div class="card-body">
							<p spellcheck="true" class="card_paragraph">
								Our philosophy lies in our mission of earnestly imparting knowledge and skill to our students. We wish to cater to the academic needs of interested individuals who are searching for high quality education. We aim to produce graduates that are competitive in the current global trends. Likewise, as an academic institution , we aim to develop young minds to become God-fearing, inteligent and multiskilled individuals who will be worthy citizens in the coming years.<br/><br/>
								In line with our mission, we envisioned to become as excellent academic and technological training ground for our learners while incorporating love and concern for society and country.
					    </p>
				  	</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card mt-3">
						<div class="card-header card_header">	
							<span class="card_title">&nbsp;<i>CORE VALUES</i></span>
						</div>
						<div class="card-body">
							<table class="table table-bordered word-warp"> 
								<tbody>
									<tr>
										<td class="td_title"><i><b>GODLINESS</b></i></td>
										<td class="td_desc">GMCians should put God first in everything they do.</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>OBEDIENCE</b></i></td>
										<td class="td_desc">
											GMCians should submit to the authorities and comply to the policies that were being implemented not only by the school but also by the society.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>LOVE</b></i></td>
										<td class="td_desc">
											GMCians should show compassion to other people inside and outside the school premises.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>DILIGENCE</b></i></td>
										<td class="td_desc">GMCians are expected to work hard and persevere.</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>EXCELLENCE</b></i></td>
										<td class="td_desc">
											GMCians should strive to develop their knowledge and skills and excel in everything that they do to achieve their full potential.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>NURTURE</b></i></td>
										<td class="td_desc">GMCians should nourish and take care of their environment.</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>MOTIVATION</b></i></td>
										<td class="td_desc">
											GMCians should share encouragement to one another to boost their morale.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>INTEGRITY</b></i></td>
										<td class="td_desc">
											GMCians should possess moral sprightness and word of honor.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>NATIONALISM</b></i></td>
										<td class="td_desc">
											GMCians will be molded to be loyal Filipino citizen with pride and make our country proud.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>DEDICATION</b></i></td>
										<td class="td_desc">
											GMCians should devote and commit themselves in their chosen field.
										</td>
									</tr>
									<tr>
										<td class="td_title"><i><b>SERVICE</b></i></td>
										<td class="td_desc">
											GMCians are expected to serve others to give back the skills, knowledge and values they gained by helping others.
										</td>
									</tr>	
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</main>